# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 04:38
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.Post.get_image_path),
        ),
    ]
